[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vzt = "CKcGMRrapsGMWmJQq6tgsRyRauDjxjyn6rCL7u6xejYa"

[programs.mainnet]
vzt = "CKcGMRrapsGMWmJQq6tgsRyRauDjxjyn6rCL7u6xejYa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 100000 tests/**/*.ts"