// ==========================================================================
// KAMUS DATA MULTI-BAHASA TERPUSAT PROVIZTO (7 BAHASA - FULL ECOSYSTEM)
// ==========================================================================
const kamusEkosistem = {
    en: {
        // --- HALAMAN UTAMA (index.html) ---
        heroTitle: "Next-Gen DeFi Yield Optimizer on Base",
        heroSubtitle: "Maximize your crypto assets automatically with hyper-efficient gas fees.",
        btnLaunchApp: "Launch Console",

        // --- HALAMAN UTAMA APLIKASI (app.html) ---
        menuDashboard: "📊 Dashboard",
        menuSwap: "🔄 Swap (DEX)",
        menuVaults: "🌾 Vaults (Optimizer)",
        menuGov: "🔒 veVZT Governance",
        btnBackHome: "← Back to Home",
        baseConnected: "Base Network Connected",
        copyright: "© 2026 PROVIZTO. All rights reserved.",
        consoleAccount: "Console Account",
        connectWallet: "Connect Wallet",
        disconnectWallet: "Disconnect",
        cardNetWorth: "Net Worth / Total Portfolio",
        cardBalance: "Available Wallet Balance",
        cardTvl: "Platform TVL (Base L2)",
        yieldTrend: "Yield Earnings Trend",
        assetAlloc: "Asset Allocation",
        recentAct: "Recent Activity",
        tblAction: "Action Type",
        tblValue: "Value / Amount",
        tblStatus: "Status / Explorer",
        swapTitle: "Swap Tokens",
        swapFrom: "From",
        swapTo: "To (Estimated)",
        btnSwapAction: "Swap Assets",
        vaultName: "Vault Name",
        vaultTvl: "Total Deposited (TVL)",
        vaultYourBal: "Your Balance",
        btnDeposit: "Deposit",
        btnManage: "Manage",
        toastTitle: "Transaction Successful",
        toastDesc: "Action processed on Base L2 network successfully.",

        // --- HALAMAN REFERRAL (referral.html) ---
        tabRegular: "Regular User",
        tabKol: "KOL / Influencer",
        sybilTitle: "🛡️ Sybil Protection Rules (Regular User)",
        sybilRule1: "• Referee must perform min. $10 swap on DEX.",
        sybilRule2: "• Lock assets in Yield Optimizer for min. 7 days.",
        massTitle: "🛡️ Mass Volume Protection Rules (KOL / Influencer)",
        massRule1: "• Total aggregate monthly volume from followers min. $2,500.",
        massRule2: "• Total aggregate TVL deposited min. $1,000.",
        yourRefLink: "🔗 Your Referral Link",
        btnCopy: "Copy Link",
        milestoneTitle: "🎁 Milestone-Based Rewards",
        summaryTitle: "📊 Account Summary",
        totalClicks: "Total Links Clicked",
        verifiedWallets: "Verified Valid/Active",
        pendingComm: "Pending Commission",
        btnClaimComm: "Claim Rewards",
        projectFaq: "ℹ️ Project FAQ",
        refHistTitle: "👥 Referral Validation History",
        colCommMetric: "Community Aggregate Metric",
        colMinReq: "Min Requirement",
        colCurrentAch: "Current Achievement"
    },
    id: {
        // --- HALAMAN UTAMA (index.html) ---
        heroTitle: "Pengoptimal Hasil DeFi Generasi Baru di Base",
        heroSubtitle: "Maksimalkan aset kripto Anda secara otomatis dengan biaya gas yang sangat efisien.",
        btnLaunchApp: "Luncurkan Konsol",

        // --- HALAMAN UTAMA APLIKASI (app.html) ---
        menuDashboard: "📊 Dasbor",
        menuSwap: "🔄 Tukar (DEX)",
        menuVaults: "🌾 Brankas (Optimizer)",
        menuGov: "🔒 Tata Kelola veVZT",
        btnBackHome: "← Kembali ke Beranda",
        baseConnected: "Jaringan Base Terhubung",
        copyright: "© 2026 PROVIZTO. Hak cipta dilindungi undang-undang.",
        consoleAccount: "Konsol Akun",
        connectWallet: "Hubungkan Dompet",
        disconnectWallet: "Putuskan",
        cardNetWorth: "Total Portofolio / Kekayaan Bersih",
        cardBalance: "Saldo Dompet yang Tersedia",
        cardTvl: "TVL Platform (Base L2)",
        yieldTrend: "Tren Pendapatan Hasil (Yield)",
        assetAlloc: "Alokasi Distribusi Aset",
        recentAct: "Aktivitas Terakhir",
        tblAction: "Jenis Tindakan",
        tblValue: "Nilai / Jumlah",
        tblStatus: "Status / Penjelajah",
        swapTitle: "Tukar Token",
        swapFrom: "Dari",
        swapTo: "Ke (Estimasi)",
        btnSwapAction: "Tukar Aset",
        vaultName: "Nama Brankas",
        vaultTvl: "Total Disetor (TVL)",
        vaultYourBal: "Saldo Anda",
        btnDeposit: "Setor",
        btnManage: "Kelola",
        toastTitle: "Transaksi Berhasil",
        toastDesc: "Aksi berhasil diproses pada jaringan Base L2.",

        // --- HALAMAN REFERRAL (referral.html) ---
        tabRegular: "Pengguna Reguler",
        tabKol: "KOL / Influencer",
        sybilTitle: "🛡️ Aturan Perlindungan Sybil (Pengguna Reguler)",
        sybilRule1: "• Orang yang dirujuk wajib melakukan swap min. $10 di DEX.",
        sybilRule2: "• Kunci aset di Yield Optimizer minimal selama 7 hari.",
        massTitle: "🛡️ Aturan Perlindungan Volume Massal (KOL / Influencer)",
        massRule1: "• Total akumulasi volume bulanan dari pengikut min. $2,500.",
        massRule2: "• Total akumulasi TVL yang disetor oleh pengikut min. $1,000.",
        yourRefLink: "🔗 Tautan Referral Anda",
        btnCopy: "Salin Tautan",
        milestoneTitle: "🎁 Hadiah Berbasis Pencapaian",
        summaryTitle: "📊 Ringkasan Akun",
        totalClicks: "Total Tautan Diklik",
        verifiedWallets: "Terverifikasi Valid/Aktif",
        pendingComm: "Komisi Tertunda",
        btnClaimComm: "Klaim Hadiah",
        projectFaq: "ℹ️ FAQ Proyek",
        refHistTitle: "👥 Riwayat Validasi Referral",
        colCommMetric: "Metrik Kumulatif Komunitas",
        colMinReq: "Batas Minimum",
        colCurrentAch: "Pencapaian Saat Ini"
    },
    zh: {
        // --- HALAMAN UTAMA (index.html) ---
        heroTitle: "Base链上的次世代DeFi收益优化器",
        heroSubtitle: "以超高能效的Gas费用自动最大化您的加密资产。",
        btnLaunchApp: "启动控制台",

        // --- HALAMAN UTAMA APLIKASI (app.html) ---
        menuDashboard: "📊 控制台",
        menuSwap: "🔄 闪兑 (DEX)",
        menuVaults: "🌾 机枪池 (Optimizer)",
        menuGov: "🔒 veVZT 治理",
        btnBackHome: "← 返回首页",
        baseConnected: "Base 网络已连接",
        copyright: "© 2026 PROVIZTO. 保留所有权利。",
        consoleAccount: "账户控制台",
        connectWallet: "连接钱包",
        disconnectWallet: "断开连接",
        cardNetWorth: "总资产净值 / 投资组合",
        cardBalance: "钱包可用余额",
        cardTvl: "平台总锁定价值 (Base L2)",
        yieldTrend: "收益率趋势",
        assetAlloc: "资产配置分布",
        recentAct: "近期动态",
        tblAction: "操作类型",
        tblValue: "价值 / 金额",
        tblStatus: "状态 / 区块浏览器",
        swapTitle: "兑换代币",
        swapFrom: "从",
        swapTo: "至 (预估)",
        btnSwapAction: "兑换资产",
        vaultName: "机枪池名称",
        vaultTvl: "总锁定价值 (TVL)",
        vaultYourBal: "您的余额",
        btnDeposit: "存款",
        btnManage: "管理",
        toastTitle: "交易成功",
        toastDesc: "操作已成功在 Base L2 网络上处理。",

        // --- HALAMAN REFERRAL (referral.html) ---
        tabRegular: "普通用户",
        tabKol: "KOL / 意见领袖",
        sybilTitle: "🛡️ 女巫攻击防护规则 (普通用户)",
        sybilRule1: "• 受邀者必须在DEX上完成至少 $10 的兑换。",
        sybilRule2: "• 在收益优化器中锁仓资产至少 7 天。",
        massTitle: "🛡️ 大额交易量防护规则 (KOL / 意见领袖)",
        massRule1: "• 关注者月度总交易量至少达到 $2,500。",
        massRule2: "• 关注者总锁仓价值 (TVL) 至少达到 $1,000。",
        yourRefLink: "🔗 您的推荐链接",
        btnCopy: "复制链接",
        milestoneTitle: "🎁 基于里程碑的奖励",
        summaryTitle: "📊 账户摘要",
        totalClicks: "链接点击总数",
        verifiedWallets: "已验证有效/活跃",
        pendingComm: "待结算佣金",
        btnClaimComm: "领取奖励",
        projectFaq: "ℹ️ 项目常见问题",
        refHistTitle: "👥 推荐验证历史记录",
        colCommMetric: "社区累计指标",
        colMinReq: "最低要求",
        colCurrentAch: "当前成就"
    },
    es: {
        heroTitle: "DeFi Yield Optimizer de Próxima Generación en Base",
        heroSubtitle: "Maximice sus activos cripto automáticamente con tarifas de gas hipereficientes.",
        btnLaunchApp: "Iniciar Consola",
        menuDashboard: "📊 Panel",
        menuSwap: "🔄 Intercambio (DEX)",
        menuVaults: "🌾 Bóvedas (Optimizer)",
        menuGov: "🔒 Gobernanza veVZT",
        btnBackHome: "← Volver al Inicio",
        baseConnected: "Red Base Conectada",
        copyright: "© 2026 PROVIZTO. Reservados todos los derechos.",
        consoleAccount: "Consola de Cuenta",
        connectWallet: "Conectar Billetera",
        disconnectWallet: "Desconectar",
        cardNetWorth: "Patrimonio Neto / Portafolio Total",
        cardBalance: "Saldo de Billetera Disponible",
        cardTvl: "TVL de la Plataforma (Base L2)",
        yieldTrend: "Tendencia de Ganancias",
        assetAlloc: "Asignación de Activos",
        recentAct: "Actividad Reciente",
        tblAction: "Tipo de Acción",
        tblValue: "Valor / Cantidad",
        tblStatus: "Estado / Explorador",
        swapTitle: "Intercambiar Tokens",
        swapFrom: "Desde",
        swapTo: "A (Estimado)",
        btnSwapAction: "Intercambiar Activos",
        vaultName: "Nombre de Bóveda",
        vaultTvl: "Total Depositado (TVL)",
        vaultYourBal: "Su Saldo",
        btnDeposit: "Depositar",
        btnManage: "Gestionar",
        toastTitle: "Transacción Exitosa",
        toastDesc: "Acción procesada en la red Base L2 con éxito.",
        tabRegular: "Usuario Regular",
        tabKol: "KOL / Influencer",
        sybilTitle: "🛡️ Reglas de Protección Sybil (Usuario Regular)",
        sybilRule1: "• El refreído debe realizar un intercambio mín. de $10 en DEX.",
        sybilRule2: "• Bloquear activos en Yield Optimizer por un mín. de 7 días.",
        massTitle: "🛡️ Reglas de Protección de Volumen Masivo (KOL / Influencer)",
        massRule1: "• Volumen mensual agregado total de seguidores mín. $2,500.",
        massRule2: "• TVL agregado total depositado mín. $1,000.",
        yourRefLink: "🔗 Su Enlace de Referencia",
        btnCopy: "Copiar Enlace",
        milestoneTitle: "🎁 Premios Basados en Metas",
        summaryTitle: "📊 Resumen de Cuenta",
        totalClicks: "Total de Clics en Enlaces",
        verifiedWallets: "Verificado Válido/Activo",
        pendingComm: "Comisión Pendiente",
        btnClaimComm: "Reclamar Premios",
        projectFaq: "ℹ️ Preguntas Frecuentes",
        refHistTitle: "👥 Historial de Validación de Referidos",
        colCommMetric: "Métrica Agregada de la Comunidad",
        colMinReq: "Requisito Mínimo",
        colCurrentAch: "Logro Actual"
    },
    vi: {
        heroTitle: "Trình Tối Ưu Hóa Lợi Nhuận DeFi Thế Hệ Mới Trên Base",
        heroSubtitle: "Tự động tối đa hóa tài sản mã hóa của bạn với phí gas siêu hiệu quả.",
        btnLaunchApp: "Mở Bảng Điều Khiển",
        menuDashboard: "📊 Bảng điều khiển",
        menuSwap: "🔄 Giao dịch (DEX)",
        menuVaults: "🌾 Kho lưu trữ (Optimizer)",
        menuGov: "🔒 Quản trị veVZT",
        btnBackHome: "← Quay lại Trang chủ",
        baseConnected: "Đã kết nối mạng Base",
        copyright: "© 2026 PROVIZTO. Bản quyền đã được bảo hộ.",
        consoleAccount: "Bảng Điều Khiển Tài Khoản",
        connectWallet: "Kết Nối Ví",
        disconnectWallet: "Ngắt kết nối",
        cardNetWorth: "Giá Trị Tài Sản Ròng / Tổng Danh Mục",
        cardBalance: "Số Dư Ví Khả Dụng",
        cardTvl: "Tổng Giá Trị Khóa Platform (Base L2)",
        yieldTrend: "Xu Hướng Lợi Nhuận",
        assetAlloc: "Phân Bổ Tài Sản",
        recentAct: "Hoạt Động Gần Đây",
        tblAction: "Loại Hành Động",
        tblValue: "Giá Trị / Số Lượng",
        tblStatus: "Trạng Thái / Trình Khám Phá",
        swapTitle: "Hoán Đổi Token",
        swapFrom: "Từ",
        swapTo: "Đến (Ước tính)",
        btnSwapAction: "Hoán Đổi Tài Sản",
        vaultName: "Tên Kho Lưu Trữ",
        vaultTvl: "Tổng Giá Trị Đã Gửi (TVL)",
        vaultYourBal: "Số Dư Của Bạn",
        btnDeposit: "Gửi Tiền",
        btnManage: "Quản Lý",
        toastTitle: "Giao Dịch Thành Công",
        toastDesc: "Hành động đã được xử lý thành công trên mạng Base L2.",
        tabRegular: "Người Dùng Thường",
        tabKol: "KOL / Người Ảnh Hưởng",
        sybilTitle: "🛡️ Quy Tắc Bảo Vệ Chống Tấn Công Sybil (Người Dùng Thường)",
        sybilRule1: "• Người được giới thiệu phải thực hiện swap tối thiểu $10 trên DEX.",
        sybilRule2: "• Khóa tài sản trong Trình tối ưu hóa lợi nhuận tối thiểu 7 ngày.",
        massTitle: "🛡️ Quy Tắc Bảo Vệ Khối Lượng Lớn (KOL / Người Ảnh Hưởng)",
        massRule1: "• Tổng khối lượng giao dịch hàng tháng của người theo dõi tối thiểu $2,500.",
        massRule2: "• Tổng TVL tích lũy được gửi từ người theo dõi tối thiểu $1,000.",
        yourRefLink: "🔗 Liên Kết Giới Thiệu Của Bạn",
        btnCopy: "Sao Chép",
        milestoneTitle: "🎁 Phần Thưởng Theo Cột Mốc",
        summaryTitle: "📊 Tóm Tắt Tài Khoản",
        totalClicks: "Tổng Số Lượt Click Liên Kết",
        verifiedWallets: "Xác Minh Hợp Lệ/Hoạt Động",
        pendingComm: "Hoa Hồng Đang Chờ",
        btnClaimComm: "Nhận Phần Thưởng",
        projectFaq: "ℹ️ FAQ Dự Án",
        refHistTitle: "👥 Lịch Sử Xác Minh Giới Thiệu",
        colCommMetric: "Số Liệu Tổng Hợp Cộng Đồng",
        colMinReq: "Yêu Cầu Tối Thiểu",
        colCurrentAch: "Đạt Được Hiện Tại"
    },
    ja: {
        heroTitle: "Baseチェーン上の次世代DeFi収益最適化プラットフォーム",
        heroSubtitle: "非常に効率的なガス代で、暗号資産を自動的に最大化します。",
        btnLaunchApp: "コンソールを起動",
        menuDashboard: "📊 ダッシュボード",
        menuSwap: "🔄 スワップ (DEX)",
        menuVaults: "🌾 ヴォルト (Optimizer)",
        menuGov: "🔒 veVZT ガバナンス",
        btnBackHome: "← ホームに戻る",
        baseConnected: "Base ネットワーク接続完了",
        copyright: "© 2026 PROVIZTO. All rights reserved.",
        consoleAccount: "アカウントコンソール",
        connectWallet: "ウォレットを接続",
        disconnectWallet: "切断する",
        cardNetWorth: "総資産 / ポートフォリオ",
        cardBalance: "利用可能なウォレット残高",
        cardTvl: "プラットフォーム TVL (Base L2)",
        yieldTrend: "収益率トレンド",
        assetAlloc: "資産配分ディストリビューション",
        recentAct: "最近のアクティビティ",
        tblAction: "アクションタイプ",
        tblValue: "価値 / 金額",
        tblStatus: "ステータス / エクスプローラー",
        swapTitle: "トークンスワップ",
        swapFrom: "振込元",
        swapTo: "振込先 (予想)",
        btnSwapAction: "資産をスワップする",
        vaultName: "ヴォルト名",
        vaultTvl: "預金総額 (TVL)",
        vaultYourBal: "あなたの残高",
        btnDeposit: "預金する",
        btnManage: "管理する",
        toastTitle: "トランザクション成功",
        toastDesc: "Base L2 ネットワーク上での処理が正常に完了しました。",
        tabRegular: "一般ユーザー",
        tabKol: "KOL / インフルエンサー",
        sybilTitle: "🛡️ シビル攻撃防御ルール (一般ユーザー)",
        sybilRule1: "• 被紹介者はDEXで最低10ドル相当のスワップを行う必要があります。",
        sybilRule2: "• 収益最適化ヴォルトに最低7日間資産をロックする必要があります。",
        massTitle: "🛡️ 大口ボリューム防御ルール (KOL / インフルエンサー)",
        massRule1: "• フォロワーの月間総取引量が最低 $2,500 以上であること。",
        massRule2: "• フォロワーの総ロック価値 (TVL) が最低 $1,000 以上であること。",
        yourRefLink: "🔗 あなたの紹介リンク",
        btnCopy: "リンクをコピー",
        milestoneTitle: "🎁 マイルストーン報酬",
        summaryTitle: "📊 アカウント概要",
        totalClicks: "リンククリック総数",
        verifiedWallets: "検証済みの有効・アクティブウォレット数",
        pendingComm: "保留中の報酬コミッション",
        btnClaimComm: "報酬を請求する",
        projectFaq: "ℹ️ プロジェクトFAQ",
        refHistTitle: "👥 紹介検証履歴",
        colCommMetric: "コミュニティ集計指標",
        colMinReq: "最小要件",
        colCurrentAch: "現在の実績"
    },
    ru: {
        heroTitle: "Оптимизатор доходности DeFi нового поколения на Base",
        heroSubtitle: "Максимизируйте свои криптоактивы автоматически с гипериффективной платой за газ.",
        btnLaunchApp: "Запустить Консоль",
        menuDashboard: "📊 Панель",
        menuSwap: "🔄 Обмен (DEX)",
        menuVaults: "🌾 Хранилища (Optimizer)",
        menuGov: "🔒 Управление veVZT",
        btnBackHome: "← На главную",
        baseConnected: "Сеть Base подключена",
        copyright: "© 2026 PROVIZTO. Все права защищены.",
        consoleAccount: "Консоль аккаунта",
        connectWallet: "Подключить кошелек",
        disconnectWallet: "Отключить",
        cardNetWorth: "Чистая стоимость / Общий портфель",
        cardBalance: "Доступный баланс кошелька",
        cardTvl: "Общая заблокированная стоимость (Base L2)",
        yieldTrend: "Тренды доходности",
        assetAlloc: "Распределение активов",
        recentAct: "Последняя активность",
        tblAction: "Тип действия",
        tblValue: "Значение / Сумма",
        tblStatus: "Статус / Проводник",
        swapTitle: "Обмен токенов",
        swapFrom: "Из",
        swapTo: "В (Оценка)",
        btnSwapAction: "Обменять активы",
        vaultName: "Название хранилища",
        vaultTvl: "Всего заблокировано (TVL)",
        vaultYourBal: "Ваш баланс",
        btnDeposit: "Депозит",
        btnManage: "Управлять",
        toastTitle: "Транзакция успешна",
        toastDesc: "Действие успешно обработано в сети Base L2.",
        tabRegular: "Обычный пользователь",
        tabKol: "KOL / Инфлюенсер",
        sybilTitle: "🛡️ Правила защиты от Сивиллы (Обычный пользователь)",
        sybilRule1: "• Реферал должен совершить обмен на DEX минимум на $10.",
        sybilRule2: "• Заблокировать активы в Оптимизаторе доходности минимум на 7 дней.",
        massTitle: "🛡️ Правила защиты от массового объема (KOL / Инфлюенсер)",
        massRule1: "• Общий совокупный ежемесячный объем подписчиков минимум $2,500.",
        massRule2: "• Общий совокупный внесенный TVL подписчиков минимум $1,000.",
        yourRefLink: "🔗 Ваша реферальная ссылка",
        btnCopy: "Копировать ссылку",
        milestoneTitle: "🎁 Награды за достижения",
        summaryTitle: "📊 Сводка аккаунта",
        totalClicks: "Всего кликов по ссылкам",
        verifiedWallets: "Проверенные активные кошельки",
        pendingComm: "Ожидающая комиссия",
        btnClaimComm: "Забрать награды",
        projectFaq: "ℹ️ FAQ проекта",
        refHistTitle: "👥 История валидации рефералов",
        colCommMetric: "Совокупная метрика сообщества",
        colMinReq: "Минимальное требование",
        colCurrentAch: "Текущее достижение"
    }
};

// ==========================================================================
// RUNNER CORE ENGINE - PERUBAHAN BAHASA DINAMIS GLOBAL
// ==========================================================================
function jalankanPenerjemahLokal(kodeBahasa) {
    // Kunci nilai bahasa di root node HTML
    const rootNode = document.getElementById('appNode');
    if (rootNode) rootNode.setAttribute('lang', kodeBahasa);

    // Cari dan manipulasi semua elemen yang ditandai dengan data-i18n
    const elemenTeks = document.querySelectorAll('[data-i18n]');
    elemenTeks.forEach(elemen => {
        const kunciTeks = elemen.getAttribute('data-i18n');
        
        // Eksekusi jika entri kunci valid di dalam database kamus
        if (kamusEkosistem[kodeBahasa] && kamusEkosistem[kodeBahasa][kunciTeks]) {
            elemen.innerText = kamusEkosistem[kodeBahasa][kunciTeks];
        }
    });

    // Simpan preferensi bahasa pengguna ke memori browser lokal (LocalStorage)
    localStorage.setItem('provizto_selected_lang', kodeBahasa);
}

// ==========================================================================
// MENYALAKAN TRIGGER EVENT SWITCHER & MENGUNCI EN SEBAGAI BAHASA UTAMA
// ==========================================================================
document.addEventListener("DOMContentLoaded", function() {
    const langSelector = document.getElementById('appLangSwitcher');
    
    // AMANKAN BAHASA UTAMA: Paksa gunakan 'en' jika pengguna baru pertama kali masuk
    const bahasaTersimpan = localStorage.getItem('provizto_selected_lang') || 'en';
    
    if (langSelector) {
        // Setel visual dropdown ke bahasa yang aktif
        langSelector.value = bahasaTersimpan;
        
        // Jalankan mesin penerjemah
        jalankanPenerjemahLokal(bahasaTersimpan);

        // Pasang event penangkap perubahan bahasa saat diklik manual
        langSelector.addEventListener('change', function(e) {
            jalankanPenerjemahLokal(e.target.value);
        });
    } else {
        // Jika dropdown tidak sengaja terhapus di salah satu halaman, tetap paksa running 'en'
        jalankanPenerjemahLokal(bahasaTersimpan);
    }
});
